/**
 * ‚±‚±‚Å‰æ‘œƒtƒ@ƒCƒ‹‚Ö‚ÌƒpƒX‚ðéŒ¾‚·‚é
 */
 //#define Tex_ 			L"Media/Sprite/OriginalGame_Sprite/.png"

 //15--------------------------------------------------------------------
#define Tex_Title				L"Media/Sprite/OriginalGame_Sprite/Title.png"
#define Tex_Result				L"Media/Sprite/OriginalGame_Sprite/Result.png"
//画面ーーーーーーーーーーーーーー
#define Tex_Background			L"Media/Sprite/OriginalGame_Sprite/Background.png"
#define Tex_Stage01				L"Media/Sprite/OriginalGame_Sprite/Stage/Stage01.png"
#define Tex_Stage02				L"Media/Sprite/OriginalGame_Sprite/Stage/Stage02.png"
#define Tex_Stage03				L"Media/Sprite/OriginalGame_Sprite/Stage/Stage03.png"
#define Tex_Stage04				L"Media/Sprite/OriginalGame_Sprite/Stage/Stage04.png"
#define Tex_StageBoss			L"Media/Sprite/OriginalGame_Sprite/Stage/StageBoss.png"
#define Tex_Frame_Exit			L"Media/Sprite/OriginalGame_Sprite/Frame/Frame_Exit.png"
#define Tex_Frame_Break			L"Media/Sprite/OriginalGame_Sprite/Frame/Frame_Break.png"
//VAUSーーーーーーーーーーーーーーーーー
#define Tex_Vaus_Normal			L"Media/Sprite/OriginalGame_Sprite/Vaus/Vaus.png"
#define Tex_Vaus_Normal_Shadow	L"Media/Sprite/OriginalGame_Sprite/Vaus/Vaus_Shadow.png"
#define Tex_Vaus_Expand			L"Media/Sprite/OriginalGame_Sprite/Vaus/Vaus_Expand.png"
#define Tex_Vaus_Expand_Shadow	L"Media/Sprite/OriginalGame_Sprite/Vaus/Vaus_Expand_Shadow.png"
#define Tex_Vaus_Laser			L"Media/Sprite/OriginalGame_Sprite/Vaus/Vaus_Laser.png"
#define Tex_Vaus_Laser_Shadow	L"Media/Sprite/OriginalGame_Sprite/Vaus/Vaus_Laser_Shadow.png"
#define Tex_Ball				L"Media/Sprite/OriginalGame_Sprite/Vaus/Ball.png"
#define Tex_Ball_Shadow			L"Media/Sprite/OriginalGame_Sprite/Vaus/Ball_Shadow.png"
#define Tex_Hp					L"Media/Sprite/OriginalGame_Sprite/Vaus/Hp.png"
#define Tex_Laser				L"Media/Sprite/OriginalGame_Sprite/Vaus/Laser.png"
//Colorーーーーーーーーーーーーーーーーーーー
#define Tex_Red					L"Media/Sprite/OriginalGame_Sprite/Color/Red.png"
#define Tex_Green				L"Media/Sprite/OriginalGame_Sprite/Color/Green.png"
#define Tex_Blue				L"Media/Sprite/OriginalGame_Sprite/Color/Blue.png"
#define Tex_Black				L"Media/Sprite/OriginalGame_Sprite/Color/Black.png"
#define Tex_White				L"Media/Sprite/OriginalGame_Sprite/Color/White.png"
//Blockーーーーーーーーーーーーーーーーー
#define Tex_Block				L"Media/Sprite/OriginalGame_Sprite/Block/Block.png"
#define Tex_Block_Shadow		L"Media/Sprite/OriginalGame_Sprite/Block/Shadow.png"

//Bossーーーーーーーーーーーーーーーーー
#define Tex_Boss				L"Media/Sprite/OriginalGame_Sprite/Boss.png"
#define Tex_Boss_Bullet			L"Media/Sprite/OriginalGame_Sprite/Boss_Bullet.png"
//Enemyーーーーーーーーーーーーーーーーー
#define Tex_Enemy				L"Media/Sprite/OriginalGame_Sprite/Enemy.png"
#define Tex_Enemy_Explosion		L"Media/Sprite/OriginalGame_Sprite/Enemy_Explosion.png"

//Itemーーーーーーーーーーーーーーーーー
#define Tex_Item	 			L"Media/Sprite/OriginalGame_Sprite/Item/Item.png"

//FONT
#define Tex_Header			L"Media/Sprite/OriginalGame_Sprite/Font/Header.png"
#define Tex_Number			L"Media/Sprite/OriginalGame_Sprite/Font/Number.png"
#define Tex_Alphabet		L"Media/Sprite/OriginalGame_Sprite/Font/Alphabet.png"
#define Tex_GameOver		L"Media/Sprite/OriginalGame_Sprite/Font/GameOver.png"

//Stage Block Settingーーーーーーーーーーーーーーーーー
#define Stage1    L"stage/stage1.csv"
#define Stage2    L"stage/stage2.csv"
#define Stage3    L"stage/stage3.csv"
#define Stage4    L"stage/stage4.csv"
#define Stage5	  L"stage/stage5.csv"
#define Stage6	  L"stage/stage6.csv"
#define Stage7	  L"stage/stage7.csv"
#define Stage8	  L"stage/stage8.csv"
#define Stage9	  L"stage/stage9.csv"
#define Stage10	  L"stage/stage10.csv"
#define Stage11	  L"stage/stage11.csv"
#define Stage12	  L"stage/stage12.csv"
#define Stage13	  L"stage/stage13.csv"
#define Stage14   L"stage/stage14.csv"
#define Stage15   L"stage/stage15.csv"
#define Stage16   L"stage/stage16.csv"
#define Stage17   L"stage/stage17.csv"
#define Stage18	  L"stage/stage18.csv"
#define Stage19	  L"stage/stage19.csv"
#define Stage20	  L"stage/stage20.csv"
#define Stage21	  L"stage/stage21.csv"
#define Stage22	  L"stage/stage22.csv"
#define Stage23	  L"stage/stage23.csv"
#define Stage24	  L"stage/stage24.csv"
#define Stage25	  L"stage/stage25.csv"
#define Stage26	  L"stage/stage26.csv"
#define Stage27	  L"stage/stage27.csv"
#define Stage28	  L"stage/stage28.csv"
#define Stage29	  L"stage/stage29.csv"
#define Stage30	  L"stage/stage30.csv"
#define Stage31	  L"stage/stage31.csv"
#define Stage32	  L"stage/stage32.csv"
#define StageBoss L"stage/stageBoss.csv"

//Audioーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
//#define Ball_Block			L"Media/Sounds/SFX/Ball_Block_Break.wav"
//#define Ball_Bar			L"Media/Sounds/SFX/Ball_Bar.wav"
//#define Ball_Boss			L"Media/Sounds/SFX/Ball_Boss.wav"
//#define Enemy_Explode		L"Media/Sounds/SFX/Enemy_Explode.wav"
//#define Ball_SG_Block		L"Media/Sounds/SFX/Ball_Silver_Gold_Block.wav"
//#define Boss_Dead			L"Media/Sounds/SFX/Boss_Dead.wav"
//#define Boss_Fight			L"Media/Sounds/SFX/Boss_Fight.wav"
//#define Break				L"Media/Sounds/SFX/Break.wav"
//#define Catch				L"Media/Sounds/SFX/Catch.wav"
//#define Expand				L"Media/Sounds/SFX/Expand.wav"
//#define Game_Clear			L"Media/Sounds/SFX/Game_Clear.wav"
//#define Game_Clear			L"Media/Sounds/SFX/Game_Clear.wav"
//#define Got_Laser			L"Media/Sounds/SFX/Got_Laser.wav"
//#define Player_Dead			L"Media/Sounds/SFX/Player_Dead.wav"
//#define Round_Start			L"Media/Sounds/SFX/Round_Start.wav"
//#define Shoot_Laser			L"Media/Sounds/SFX/Shoot_Laser.wav"
//#define Start_Game			L"Media/Sounds/SFX/Start_Game.wav"
//Audio_char*---------------------------------------------------
#define Ball_Block			"Media/Sounds/SFX/Ball_Block_Break.wav"
#define Ball_Bar			"Media/Sounds/SFX/Ball_Bar.wav"
#define Ball_Boss			"Media/Sounds/SFX/Ball_Boss.wav"
#define Enemy_Explode		"Media/Sounds/SFX/Enemy_Explode.wav"
#define Ball_SG_Block		"Media/Sounds/SFX/Ball_Silver_Gold_Block.wav"
#define Boss_Dead			"Media/Sounds/SFX/Boss_Dead.wav"
#define Boss_Fight			"Media/Sounds/SFX/Boss_Fight.wav"
#define Break				"Media/Sounds/SFX/Break.wav"
#define Catch				"Media/Sounds/SFX/Catch.wav"
#define Expand				"Media/Sounds/SFX/Expand.wav"
#define Game_Clear			"Media/Sounds/SFX/Game_Clear.wav"
#define Game_Over			"Media/Sounds/SFX/Game_Over.wav"
#define Got_Laser			"Media/Sounds/SFX/Got_Laser.wav"
#define Player_Dead			"Media/Sounds/SFX/Player_Dead.wav"
#define Round_Start			"Media/Sounds/SFX/Round_Start.wav"
#define Shoot_Laser			"Media/Sounds/SFX/Shoot_Laser.wav"
#define Start_Game			"Media/Sounds/SFX/Start_Game.wav"

#define CLEAR				"Media/Sounds/clear.wav"
